#ifndef COMMAND_H
#define COMMAND_H
#include "common/Common.h"
enum cmdType {
    NONE = 0,
    APP = 0XFE,
    BL = 0XFF,
};
enum cmdCode {
    CMD_TYPE_APP = 0x10,
    CMD_CODE_OPEN,
    CMD_CODE_TEMP,
    CMD_CODE_SUCCESS,
    CMD_CODE_APPARATUS,
    CMD_CODE_APPARATUS_ACHIEVE,
    CMD_CODE_INITAILIZE,
    CMD_CODE_CONNECT,
    CMD_CODE_INFUSION,
    CMD_CODE_WASH,
    CMD_CODE_INJECT,
    CMD_CODE_WARM_TEMP,
    CMD_CODE_WARM_TIME,
    CMD_CODE_WARM_BLOCK1,
    CMD_CODE_WARM_BLOCK2,
    CMD_CODE_CARVE_DIRECTION,
    CMD_CODE_CARVE_RESET,
    CMD_CODE_WARM_BUMP,
    CMD_CODE_CARVE_BUMP,
    CMD_CODE_DEBUG,
    CMD_CODE_NORMAL,

    CMD_CODE_AIR_CYLINDER1,
    CMD_CODE_AIR_CYLINDER2,
    CMD_CODE_AIR_CYLINDER3,
    CMD_CODE_AIR_CYLINDER4,

    CMD_CODE_INJUCET_BUMP,
    CMD_CODE_PRESS_PLATE,

    CMD_CODE_INJUCET_VOLUME1,
    CMD_CODE_INJUCET_VOLUME2,
    CMD_CODE_INJUCET_VOLUME3,
    CMD_CODE_INJUCET_VOLUME4,
    CMD_CODE_INJUCET_VOLUME5,
    CMD_CODE_INJUCET_VOLUME6,
    CMD_CODE_INJUCET_VOLUME7,

    CMD_CODE_RETURN_ZERO,
    CMD_CODE_BUMP_INT,
    CMD_CODE_BUMP_FILLING,

    CMD_CODE_INJUCET_TIME,
};
#endif // COMMAND_H
