#ifndef COMMAND_H
#define COMMAND_H
#include "common/Common.h"
enum cmdType {
    NONE = 0,
    APP = 0XFE,
    BL = 0XFF,
};
enum cmdCode {
    CMD_TYPE_APP = 0x10,
    CMD_CODE_SUCCESS,
    CMD_CODE_CONNECT,
    CMD_CODE_WASH,
    CMD_CODE_BUMP_FILLING,

    CMD_CODE_INJUCET_VOLUME_R1,
    CMD_CODE_INJUCET_VOLUME_R2,
    CMD_CODE_INJUCET_VOLUME_M,
    CMD_CODE_INJUCET_VOLUME_W1,
    CMD_CODE_INJUCET_VOLUME_W2,
    CMD_CODE_INJUCET_VOLUME_W3,
    CMD_CODE_INJUCET_VOLUME_W4,
    CMD_CODE_INJUCET_VOLUME_W5,
    CMD_CODE_INJUCET_VOLUME_W6,
    CMD_CODE_INJUCET_VOLUME_BASE,

};
#endif // COMMAND_H
